on:
  rss:
    url:
      - https://feeds.feedburner.com/ruanyifeng
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          title: ${{on.rss.outputs.title}}
          contentSnippet: ${{on.rss.outputs.contentSnippet}}
          link: ${{on.rss.outputs.link}}
        run: |
          echo title: $title
          echo contentSnippet: $contentSnippet
          echo link: $link
      - name: Make a HTTP Request
        uses: actionsflow/axios@v1
        with:
          url: ${{secrets.CUBOX_API}}
          method: POST
          body: |
            {
             "type":"url",
             "link":"${{ on.rss.outputs.link }}",
             "content":"<<<${{on.rss.outputs.contentSnippet}}>>>",
             "title": "${{ on.rss.outputs.title }}",
             "folder":"RSS"
            }
